apiVersion: apps/v1
kind: Deployment
metadata:
  name: chai-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chai-app
  template:
    metadata:
      labels:
        app: chai-app
    spec:
      containers: vickeys/tetris:v1-16
      - name: chai-app
        image: 
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
