apiVersion: apps/v1
kind: Deployment
metadata:
  name: chai-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chai-app
  template:
    metadata:
      labels:
        app: chai-app
    spec:
      containers:
      - name: chai-app
        image: vickeys/boardgame:main-7
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
